### ISSUE TITLE
Can't Figure Out How to Get PPC Check to Work in ShinyStan, and Unable to Locate Supplementary Material from Journal Article

### ISSUE THREAD

**Issue by mbmriver1** [fweber144/shinybrms#1]
https://journal.r-project.org/issues/2022-2/

Your journal article found above mentions supplementary material (files mentioned in the paper include: Supplement_sections.pdf, CAP.csv, weber_shinybrms.R, and weber_shinybrms_sessionInfo.txt). The journal article does not mention where they are saved, and the journal.r_project.org site does not seem to have the files saved there. Where can I access these files?

The main reason I want to access the files is to troubleshoot the posterior predictive checks in shinystan. My understanding is that the stan code generated by shinybrms automatically produces the required code to enable the PPC check in the generated quantities section. I don't know if I am doing something wrong when I generate my models in shinybrms, but I can never seem to get the PPC section of shinystan to work. I wanted to run the example from the paper to see if I can reproduce the PPC results from the paper.

Thank you for creating this application, it has the best balance of user-friendliness and capability out of all the Bayesian linear regression tools I have seen.

**Comment by fweber144** [comment]
Thank you! You are right that the files don't seem to be accessible anymore from the R Journal's website. Originally, they were, but it seems the R Journal has changed the layout and other aspects of the website (e.g., originally a PDF of the paper was shown, not an HTML version). I'll ask the editor what to do about it. Until then, you can find the supplement files attached here.

[weber_shinybrms_2024_supplement.zip](https://github.com/user-attachments/files/16998834/weber_shinybrms_2024_supplement.zip)

Concerning the PPC:

> My understanding is that the stan code generated by shinybrms automatically produces the required code to enable the PPC check in the generated quantities section.

You don't need the Stan code or the generated quantities for this. Within shinystan, under "Diagnose → PPcheck", you can select the appropriate data as described in the last enumeration point of [this screenshot](https://fweber144.github.io/shinybrms/articles/screenshots/Posterior_shinystan.png).

**Comment by mbmriver1** [comment]
Thank you for sending along the supplementary files! I like the frequentist comparison in particular.

I'm still having difficulties using the PPCheck with the CAP.csv example. I'll add some screenshots of what I am seeing.

In the image below, I show the 'Default Summary' from my instance of fitting the model in the paper. It looks like my results are comparable to yours (Figure 9). This leads me to believe I haven't made any errors reproducing the example.
![Capture1](https://github.com/user-attachments/assets/03b8cf2f-b448-49cd-8104-34b423783c68)

In the image below, I show the 'Select data' tab in ShinyStan's 'Graphical posterior predictive checks' tab. I couldn't find an example of how to fill in the fields, but I think I filled them in correctly. I have b_age in the screenshot, but I tried other parameters as well.
![Capture2](https://github.com/user-attachments/assets/aee2ac5f-2662-4f70-9dd3-f9ac2b7fda5b)

In the image below, I show the 'Distributions of observed data and a random sample of replications' tab. I get the error 'y_rep can only be specified once' no matter what bubbles I have filled in.
![Capture3](https://github.com/user-attachments/assets/57d9dbc3-4990-459f-9b78-9eff81d8ffa2)

In the image below, I show the 'Distributions of test statistics' tab. I get the same error.
![Capture4](https://github.com/user-attachments/assets/9390fb08-39f4-4fec-9831-310ddfbecc34)

I don't have any issues with any other part of ShinyStan. For example,the image below shows a summary of the chains in ShinyStan.
![Capture5](https://github.com/user-attachments/assets/7f39a9db-3753-4782-aff8-9ceefe9b6b83)

I guess the issue could be on my end, or in shinystan or shinybrms. Regardless, I hope you can help me figure out the source of the issue. Thanks!

**Comment by mbmriver1** [comment]
Thanks for the supplementary materials, and I figured out the PP_check, so thanks!
